version: '3.8'

services:
  # The Django Application
  web:
    build: .
    command: /app/entrypoint.sh
    volumes:
      - .:/app 
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    environment:
      - DB_HOST=db
      - DB_NAME=saas_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  # The Database (Postgres)
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=saas_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # Redis (For Caching/Throttling/Celery)
  redis:
    image: redis:7-alpine

volumes:
  postgres_data: